### ISSUE TITLE
Questions about evaluation

### ISSUE THREAD

**Issue by JunrQ** [cvlab-stonybrook/SID#1]
Hello, thanks for the code, it really helps.

Can you provide the function about calculating the RMSE?

**Comment by hieulem** [comment]
Hi,

Can you reply with your email? I will send the evaluation code to you.

**Comment by JunrQ** [comment]
zhou0365@e.ntu.edu.sg

Thank you~

**Comment by kuldeeppurohit** [comment]
Hi,
Could you send the RMSE evaluation code to me too? I can receive it at kuldeeppurohit3@gmail.com 
or 
purohitk@msu.edu

I intend to perform quantitative and qualitative comparison with your work in my paper.

Thank you

**Comment by tiffanyXiaoqing** [comment]
Hello, I also hope to get the RMSE evaluation code. Can you send it to me?
My email address is xqshen@whu.edu.cn

Thank you!

**Comment by hy-zpg** [comment]
Hello, I also hope to get the evaluation code by using shadow mask predictor. Can you send it to me?
My email address is yanhong.sjtu@gmail.com

Thank you!

**Comment by penguinbing** [comment]
Hello, I hope to get the RMSE evaluation code. Can you send it to me?
My email address is penguinbing@gmail.com

Thank you very much!

**Comment by hy-zpg** [comment]
hello, the code is attached.

**Comment by GqqGGqqG** [comment]
Hello, I am hope to get the RMSE evaluation code. Can you send it to me?
My email address is guoqing2017@whu.edu.cn

Thank you very much!

**Comment by hieulem** [comment]
We just updated the front page with information regarding this evaluation code.

**Comment by zhuyr97** [comment]
Ask for evaluation code, thank you! My email address is zyr@mail.ustc.edu.cn
