### ISSUE TITLE
ISTD+ dataset

### ISSUE THREAD

**Issue by sunwonkang** [cvlab-stonybrook/SID#11]
Where is the script for 'adjusted ISTD dataset'? Is that the augmentation code in data_processing? But it doesn't work. Please help me. Thank you.

**Comment by hieulem** [comment]
Hi @sunwonkang , can you try to use this script from our ICCV19 submission:

[color_adjustment_code.zip](https://github.com/cvlab-stonybrook/SID/files/7117543/color_adjustment_code.zip)

**Comment by hieulem** [comment]
https://drive.google.com/file/d/1rsCSWrotVnKFUqu9A_Nw9Uf-bJq_ryOv/view?usp=sharing
