### ISSUE TITLE
Could you provide the mask utilized for testing in TPAMI2020 work?

### ISSUE THREAD

**Issue by jinwan1994** [cvlab-stonybrook/SID#14]

**Comment by hieulem** [comment]
Hi, thank you for bringing this up! I think I forgot to include this in the TPAMI work...

I used masks from the MTMT method: 

https://github.com/eraserNut/MTMT

https://drive.google.com/file/d/1BK4x9IUNQKBaP7ye5S2-e9_zEN7FbZUg/view

**Comment by jinwan1994** [comment]
Thank you very much!
