### ISSUE TITLE
Questions about shadow parameters predictions

### ISSUE THREAD

**Issue by JunrQ** [cvlab-stonybrook/SID#2]
Hello, I have some questions about the code, what's the reason doing following rescale on shadow parameters predcition?

https://github.com/lmhieu612/SID/blob/8f62eda96f0154e0eff20b1ab02128009122fa4b/src/models/SID_model.py#L86

https://github.com/lmhieu612/SID/blob/8f62eda96f0154e0eff20b1ab02128009122fa4b/src/models/SID_model.py#L121

**Comment by hieulem** [comment]
Well spotted!

I am so sorry, these lines shouldn't be here for this code. These are for our extended version for a journal. 

Basically, we restrict the values of the parameters similar to how we did it for our ECCV paper. The first line is to project a normalized range [-1,1] to [1,5] which is what we believe is proper for the scaling factors. They are still experimental at this point but we are seeing a significant performance boost with this simple trick. 

You can simply ignore them or comment them out (if so, please do the same for the parameter estimator in the python notebook). Sorry for pushing some experimental stuff here, I will do more cleaning after CVPR. 

Best,
