### ISSUE TITLE
Question about the augmented ISTD dataset

### ISSUE THREAD

**Issue by tiffanyXiaoqing** [cvlab-stonybrook/SID#3]
The effect of your paper on shadow removal is particularly good, so I hope I can reproduce this result and learn more from it. 
I found that the RMSE drops by 6% after dataset augmentation. Can you share the augmented dataset to me?
Thank you!

**Comment by hieulem** [comment]
Please check the new ipython notebook I have just uploaded :) 

https://github.com/lmhieu612/SID/blob/main/data_processing/dataset_augmentation.ipynb
