### ISSUE TITLE
How to train this model on customer dataset

### ISSUE THREAD

**Issue by Sylvia-Vee** [cvlab-stonybrook/SID#4]
Hi, 
I want to try this model on customer dataset, as the readme.txt instruct, I need generate param.txt first, but I'm a little confused about what the  'sdfree_path=train_c_fixed_ours' means

looking forward to your response

**Comment by hieulem** [comment]
Hi,

This is the path to shadow-free images. This is a fully-supervised method and we need those to train the model.

**Comment by Sylvia-Vee** [comment]
Okay~ Thanks a lot
