### ISSUE TITLE
How to obtain input['penumbra']?

### ISSUE THREAD

**Issue by yliu1082** [cvlab-stonybrook/SID#6]
I am training the model SIDPAMIwinp with my own dataset and got the following issue:

Traceback (most recent call last):
  File "../SID_train.py", line 31, in <module>
    model.set_input(data)
  File "/home/Research_Projects/SID/src/models/SIDPAMIwinp_model.py", line 83, in set_input
    self.penumbra = input['penumbra'].to(self.device).type(torch.float)
KeyError: 'penumbra'

I checked all the files in 'data' folder but there is no operation to obtain input['penumbra']. Could you please explain how to get this? Thank you very much!

**Comment by hieulem** [comment]
Sorry for the confusion, I have updated the data loader file, which computes the penumbra.
